### ISSUE TITLE
ERR_FEATURE_UNAVAILABLE_ON_PLATFORM

### ISSUE THREAD

**Issue by dPacc** [Debdut/browser-extension#12]
Hi @Debdut , the latest commit is throwing this error when we run `npm run start BROWSER` command. It was running during the previous vite build.

```
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
```

I have tried switching the Node.js versions to v16.17.0, v18.13.0. But it still doesn't work. Any idea on how to fix this?

Here is what I found on StackOverflow: https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform

**Comment by Debdut** [comment]
are you on linux? run `uname -a` and post the result here

**Comment by dPacc** [comment]
This is the output

`
Linux omen 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by icheered** [comment]
Any updates on this topic? I'm having the same issue

**Comment by Debdut** [comment]
@nascarsayan can you test this on a linux VM?

**Comment by nascarsayan** [comment]
I looked into the issue. 
The issue is coming in Ubuntu with Linux Kernel version `5.15.0-60-generic` with both nodejs `v16.18.1` and `v18.13.0`. I performed ubuntu upgrade from 20 to 22, which upgraded Linux version to `5.15.15-051515-generic`, but still seeing the same issue.
I had earlier tested out `browser-extension` in pop-os `v20.04` where the linux kernel version was `5.15.15-76051515-generic`, where it was working fine.

`fs.watch` recursive was not supported in Linux.
I think this might be a limitation of fs.watch, and the same is mentioned in the nodejs docs [here](https://nodejs.org/docs/latest-v18.x/api/fs.html#caveats). The limitation is mentioned both in nodejs `v16` and `v18`. However, in [this PR](https://github.com/nodejs/node/pull/45098) they have added the support for recursive file watch in Linux.

This [stackoverflow article](https://stackoverflow.com/a/13705878/7625884) recommends using chokider instead of `fs.watch` for better cross-platform support, including recursive watch.
@Debdut, We might need to use `chokider` here as a dev-dependency instead of `fs.watch` (and add another external npm dependency, phew!) to support all Linux versions.

**Comment by icheered** [comment]
@nascarsayan thanks for looking into it. I also tried using chokidar and it is practically a drop-in replacement (`fs.watch` -> `chokidar.watch`) however there is an issue with the block of code that watches the public files folder. I'm currently on my phone so I can't give more info, but I couldn't get that to work within a few minutes.

**Comment by Debdut** [comment]
@nascarsayan another dependency, phew 😮‍💨 

@icheered let me know

**Comment by nascarsayan** [comment]
`node-watch` is working on Linux.
